### ISSUE TITLE
[BUG] Test suite failing with equinox 0.11.10

### ISSUE THREAD

**Issue by GaetanLepage** [patrick-kidger/lineax#118]
Context: [bumping equinox in nixpkgs](https://github.com/NixOS/nixpkgs/pull/363128)

When using the latest version of equinox (0.11.10), several tests in `tests/test_vmap_vmap.py` fail with:
```
AttributeError: module 'equinox.internal' has no attribute 'if_mapped'
```

Is an update planned to ensure compatibility with equinox ?

Thanks a lot in advance.
-> This is not urgent in any way. I am just anticipating the issue reporting. Don't feel urged to look at this ;)

**Comment by johannahaffner** [comment]
Hi Gaetan, 

this was due to a [test case](https://github.com/patrick-kidger/lineax/blob/42cf2d8d447007b67a4b1e585c600ed5dfe833fb/tests/test_vmap_vmap.py#L126) using the [now-removed](https://github.com/patrick-kidger/equinox/pull/907/commits/c6c1a4047c832fb19d3a57543a3fc343a594d2af) `if_mapped`. Lineax itself did not actually make use of it, and therefore has remained compatible with equinox.

I just checked - `eqxi.if_mapped` can be removed from said test case on pre- and post JAX 0.4.36 and the relevant tests run with equinox 0.11.9, as well as 0.11.10. 

I'll re-run on the full test suite just in case and will open a PR, @patrick-kidger :)

**Comment by patrick-kidger** [comment]
Hehe we're looking at this at the exact time @johannahaffner . I just opened #119! :D

**Comment by johannahaffner** [comment]
:D :D

Just out of curiosity: I just set `out_axes` to the input at the same level (so for instance `vmap1_op`), what does the extra condition you included do?

**Comment by patrick-kidger** [comment]
Convert `eqx.if_array(0)` into just a `0`. Which is completely pointless on my part, because the output of `.as_matrix()` is always an array. :p

**Comment by johannahaffner** [comment]
Haha I see! Thanks :)
